apiVersion: v2
name: adapterfs
description: Expose mounted Kubernetes filesystems through web, WebDAV, SFTP, FTP and S3
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/wenisch-tech/AdapterFS
sources:
  - https://github.com/wenisch-tech/AdapterFS
annotations:
  org.opencontainers.image.source: https://github.com/wenisch-tech/helm-charts
