apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adapterfs.fullname" . }}
  labels: {{ include "adapterfs.labels" . | nindent 4 }}
data:
  application.yaml: |
    adapterfs:
      exports:
      {{- toYaml .Values.exports | nindent 8 }}
