{{- if not .Values.credentials.existingSecret }}
{{- $old := lookup "v1" "Secret" .Release.Namespace (include "adapterfs.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adapterfs.fullname" . }}
  labels: {{ include "adapterfs.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.credentials.username | b64enc | quote }}
  password: {{ if $old }}{{ index $old.data "password" }}{{ else }}{{ randAlphaNum 28 | b64enc | quote }}{{ end }}
  s3-access-key: {{ if $old }}{{ index $old.data "s3-access-key" }}{{ else }}{{ printf "AFS%s" (randAlphaNum 17) | b64enc | quote }}{{ end }}
  s3-secret-key: {{ if $old }}{{ index $old.data "s3-secret-key" }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
{{- end }}
