name: CI
on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
jobs:
  test:
    uses: ./.github/workflows/_test.yml
  image:
    needs: test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_image.yml
    permissions: {contents: read, packages: write, id-token: write, attestations: write}
  native:
    needs: test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_native.yml
    permissions: {contents: read, packages: write}
  release:
    needs: [test, image, native]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')
    uses: ./.github/workflows/_release.yml
    permissions: {contents: write, packages: write, id-token: write}
